<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{
    public function findAllEnabled()
    {
        return $this->getEntityManager()->createQuery("SELECT o FROM AppBundle:Order o WHERE o.enabled = 1")->getResult();
    }
}
